{
  "hash": "270b294c1050579da9e8bc97778c6c49",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"linearR\"\nformat: html\neditor: visual\noutput:\n  warnings = FALSE\n---\n\n\n## \n\n# Linear Regressions\n\nFirstly, a basic linear regression will be shown, with accuracy and precision measured using a variety of techniques.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load necessary libraries\nlibrary(ggplot2)\nlibrary(palmerpenguins)\nlibrary(nnet)  # Load the nnet package for multinomial logistic regression\n\n# Prepare the data\ndata(penguins)\npenguins <- na.omit(penguins)  # Remove NA values to avoid errors in modeling\n\n# Fit the multinomial logistic regression model\nmodel <- multinom(species ~ bill_length_mm, data = penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  9 (4 variable)\ninitial  value 365.837892 \niter  10 value 164.776502\niter  20 value 164.382360\nfinal  value 164.379420 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\n# Summary of the model\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nmultinom(formula = species ~ bill_length_mm, data = penguins)\n\nCoefficients:\n          (Intercept) bill_length_mm\nChinstrap   -55.76638       1.266016\nGentoo      -49.25770       1.142570\n\nStd. Errors:\n          (Intercept) bill_length_mm\nChinstrap    7.221959      0.1672115\nGentoo       6.924396      0.1616439\n\nResidual Deviance: 328.7588 \nAIC: 336.7588 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Compute predicted probabilities\npenguins$predicted_prob <- predict(model, type = \"probs\")\n\n# Create a new data frame for plotting predicted probabilities\nplot_data <- data.frame(\n  bill_length_mm = penguins$bill_length_mm,\n  species = penguins$species,\n  Chinstrap = penguins$predicted_prob[, \"Chinstrap\"],\n  Gentoo = penguins$predicted_prob[, \"Gentoo\"],\n  Adelie = penguins$predicted_prob[, \"Adelie\"]  # Add Adelie probabilities\n)\n\n# Plot predicted probabilities\nggplot(plot_data, aes(x = bill_length_mm)) +\n  geom_line(aes(y = Chinstrap, color = \"Chinstrap\"), linewidth = 1) +\n  geom_line(aes(y = Gentoo, color = \"Gentoo\"), linewidth = 1) +\n  geom_line(aes(y = Adelie, color = \"Adelie\"), linewidth = 1) +  # Add a line for Adelie\n  labs(title = \"Predicted Probability of Species by Bill Length\",\n       x = \"Bill Length (mm)\",\n       y = \"Probability\") +\n  scale_color_manual(values = c(\"Chinstrap\" = \"blue\", \"Gentoo\" = \"red\", \"Adelie\" = \"green\")) +  # Add color for Adelie\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](LinearR_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nThe model has successfully converged, indicating a stable solution with significant effects of bill length on species classification. However, the model's overall effectiveness is unclear without a baseline comparison, and its AIC of 336.7588 suggests there might be room for improvement.\n\nTo potentially improve this model:\n\n1.  **Include More Predictors**: Adding other relevant variables like bill depth or flipper length could provide a more comprehensive understanding.\n\n2.  **Model Interaction Effects**: Interactions between variables might reveal more complex relationships influencing species classification.\n\n3.  **Cross-Validation**: Use techniques like cross-validation to assess the model's performance on unseen data and avoid overfitting.\n\n4.  **Compare Models**: Evaluate other models or use different statistical approaches (like decision trees or random forests) for potentially better predictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load necessary libraries\nlibrary(palmerpenguins)  # Contains the dataset\nlibrary(nnet)            # For multinomial logistic regression\nlibrary(ggplot2)         # For plotting\n\n# Load and prepare the data\ndata(penguins)\npenguins <- na.omit(penguins)  # Remove rows with NA values to avoid errors\n\n# Fit the multinomial logistic regression model with both predictors\nmodel <- multinom(species ~ bill_length_mm + body_mass_g, data = penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  12 (6 variable)\ninitial  value 365.837892 \niter  10 value 45.771696\niter  20 value 39.757787\niter  30 value 37.919114\niter  40 value 37.764190\niter  50 value 37.729763\niter  60 value 37.726031\nfinal  value 37.719086 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\n# Summary of the model to see coefficients and statistics\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nmultinom(formula = species ~ bill_length_mm + body_mass_g, data = penguins)\n\nCoefficients:\n          (Intercept) bill_length_mm  body_mass_g\nChinstrap   -84.76389      3.3125710 -0.016076310\nGentoo      -57.63830      0.8660536  0.004585843\n\nStd. Errors:\n          (Intercept) bill_length_mm body_mass_g\nChinstrap 0.008973397      0.2040780 0.002372277\nGentoo    0.002673471      0.1033103 0.001010281\n\nResidual Deviance: 75.43817 \nAIC: 87.43817 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Optionally, plot predicted probabilities if needed\n# Compute predicted probabilities for visualization\npenguins$predicted_prob <- predict(model, type = \"probs\")\n\n# Create a new data frame for plotting predicted probabilities\nplot_data <- data.frame(\n  bill_length_mm = penguins$bill_length_mm,\n  body_mass_g = penguins$body_mass_g,\n  species = penguins$species,\n  Chinstrap = penguins$predicted_prob[, \"Chinstrap\"],\n  Gentoo = penguins$predicted_prob[, \"Gentoo\"],\n  Adelie = penguins$predicted_prob[, \"Adelie\"]\n)\n\n# Example plot: Predicted probabilities vs. bill length colored by species\nggplot(plot_data, aes(x = bill_length_mm, color = species)) +\n  geom_line(aes(y = Chinstrap), linewidth = 1, linetype = \"solid\") +\n  geom_line(aes(y = Gentoo), linewidth = 1, linetype = \"dashed\") +\n  geom_line(aes(y = Adelie), linewidth = 1, linetype = \"dotted\") +\n  labs(title = \"Predicted Probability of Species by Bill Length and Body Mass\",\n       x = \"Bill Length (mm)\",\n       y = \"Probability\") +\n  scale_color_manual(values = c(\"Chinstrap\" = \"blue\", \"Gentoo\" = \"red\", \"Adelie\" = \"green\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](LinearR_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThis model, though is looks absolutely bizzare, which includes both bill length and body mass as predictors, appears to be significantly better than the previous model that only included bill length. Here's a breakdown of why this might be the case:\n\n1.  **Improved Fit**: The final value of the residual deviance is much lower (37.719086 compared to 164.379420), indicating a much better fit to the data. Lower residual deviance generally signifies that the model explains a larger portion of the variance.\n\n2.  **Lower AIC**: The Akaike Information Criterion (AIC) has decreased from 336.7588 to 87.43817. A lower AIC value suggests that the model provides a better balance between goodness of fit and complexity, making it a more efficient model.\n\n3.  **Convergence and Iterations**: The model has iterated through more steps (60 iterations) and still converged, which often indicates that the model is effectively optimizing and dealing with more complexity.\n\n4.  **Significance of Coefficients**: The coefficients for both predictors across species are substantial, and their standard errors are quite low, indicating strong and reliable effects. Specifically, the coefficient of bill length for Chinstrap is notably high, showing a significant impact on distinguishing it from the baseline category (Adelie).\n\nThis model is better because it captures more nuances in the data by considering an additional relevant feature (body mass). It demonstrates a significant improvement in predictive accuracy and model efficiency as indicated by the lower deviance and AIC scores.\n\n**Possible Improvements:**\n\nWhile the model is already improved, further enhancements could involve:\n\n-   **Inclusion of Additional Predictors**: Further explore other measurements, such as flipper length or sex, if not already included.\n\n-   **Interaction Terms**: Investigating possible interactions between predictors might reveal more complex relationships.\n\n-   **Cross-validation**: To ensure the model's robustness and to avoid overfitting, performing cross-validation could validate these results across different subsets of data.\n\nAs demonstrated, the model can absolutely be improved through continuous refinement and more complex systems. However, the above graphs demonstrate how multi-linear regressions help to predict variables, both numerical or categorical.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}