project:
  type: website

title: "My Expert-Level Quarto Website"

format:
  html:
    theme: paper
    toc: true
    toc-depth: 3
    toc-float: 
      collapsed: false
      smooth-scroll: true
    highlight-style: github
    number-sections: true
    code-fold: true

editor: visual

output-dir: "_site"

website:
  navbar:
    title: "Final Project - Math 378"
    left:
      - text: "Home"
        href: content/index.qmd
      - text: "Data"
        href: content/data-analysis.qmd
      - text: "Linear Regression"
        href: content/LinearR.qmd
      - text: "Poem"
        href: content/poem.qmd
      - text: "Bee Movie"
        href: content/test.qmd
    right:
      - icon: fa fa-envelope
        href: "mailto:contact@myquartowebsite.com"
  favicon: "favicon.ico"

execute:
  enabled: true
  cache: true